FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache postgresql-client

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .



CMD ["sh", "-c", "npm run migrate && npm run seed:admin && npm start"]